import type { TradeAsset } from "./types";

export const TRADE_ASSETS_MOCK: TradeAsset[] = [
  {
    id: "vebtc-24m",
    name: "veBTC 24-Month Fraction",
    symbol: "veBTC-24M",
    thumbnail: "🟧",
    priceUsd: 0.947,
    volume24hUsd: 1_320_400,
    change24hPct: 2.18,
    category: "locked",
  },
  {
    id: "vebtc-12m",
    name: "veBTC 12-Month Fraction",
    symbol: "veBTC-12M",
    thumbnail: "🟨",
    priceUsd: 0.903,
    volume24hUsd: 804_210,
    change24hPct: -0.82,
    category: "locked",
  },
  {
    id: "vemezo-18m",
    name: "veMEZO 18-Month Fraction",
    symbol: "veMEZO-18M",
    thumbnail: "🟩",
    priceUsd: 0.825,
    volume24hUsd: 920_030,
    change24hPct: 1.42,
    category: "locked",
  },
  {
    id: "vemezo-30m",
    name: "veMEZO 30-Month Fraction",
    symbol: "veMEZO-30M",
    thumbnail: "🟢",
    priceUsd: 0.794,
    volume24hUsd: 641_980,
    change24hPct: -1.74,
    category: "locked",
  },
  {
    id: "fract-spot",
    name: "FRACT Spot Exposure",
    symbol: "FRACT-SPOT",
    thumbnail: "🟦",
    priceUsd: 1.102,
    volume24hUsd: 2_118_900,
    change24hPct: 3.07,
    category: "liquid",
  },
  {
    id: "fract-carry",
    name: "FRACT Carry Route",
    symbol: "FRACT-CARRY",
    thumbnail: "🟪",
    priceUsd: 1.237,
    volume24hUsd: 413_420,
    change24hPct: 0.39,
    category: "yield",
  },
  {
    id: "mezo-yield",
    name: "MEZO Yield Route",
    symbol: "MEZO-YIELD",
    thumbnail: "🟫",
    priceUsd: 0.986,
    volume24hUsd: 356_700,
    change24hPct: -0.28,
    category: "yield",
  },
  {
    id: "vebasket",
    name: "ve Balanced Basket",
    symbol: "VE-BASKET",
    thumbnail: "🧺",
    priceUsd: 1.013,
    volume24hUsd: 577_230,
    change24hPct: 1.06,
    category: "liquid",
  },
];
